/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "stm32f303xc.h"
#include "timer.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//  Program entrance
int main(void)
{
	// Board initialisation
	enable_clocks();
	initialise_board();

	// Initialise timer with delay time and callback function
	init_timer_module(TIM2, blink_all_leds);
	enable_timer2_interrupt();
	reset_timer(TIM2, 1000);


	// Uncomment to test one-shot function
	//one_shot(TIM2, 2000);

	/* Loop forever */
	for(;;) {}
}


